### PR TITLE
#166284452 Update feedback message on Events page 

### PR DESCRIPTION
**Pull request by efalayi**
#### What Does This PR Do?
This PR updates the feedback message on EventsPage when there are no upcoming events.

#### Description Of Task To Be Completed
- rename EventNotFound component to NoEvents
- rename and update scss file
- update EventsPage component

#### Any Background Context You Want To Provide?
N/A

#### How can this be manually tested?
- pull branch
- navigate to `/events`. Appropriate message should be displayed if there are no events.

#### What are the relevant pivotal tracker stories?
[#166284452](https://www.pivotaltracker.com/story/show/166284452)

#### Screenshot(s)
Screenshot 2019-06-03 at 10 40 52 AM

### CODE REVIEW

**Comment by brianbirir** [comment]
Thanks for this @efalayi . It works as expected and the code looks good.

**Comment by brianbirir** [comment]
@efalayi A few issues though:

1. When I log in, the I'm still redirected to `/dashboard` (but the `/events` path works)
2. When I click on the dashboard link at the top it redirects to `/dashboard` path.

Please correct the above

**Comment by brianbirir** [comment]
On the top of **There are no new events for today** message, please add some margin space @efalayi. A vertical alignment will be helpful.

**Comment by brianbirir** [comment]
> @efalayi A few issues though:
> 
> 1. When I log in, the I'm still redirected to `/dashboard` (but the `/events` path works)
> 2. When I click on the dashboard link at the top it redirects to `/dashboard` path.
> 
> Please correct the above

@efalayi my apologies as this will be worked on a different task, that is, [166284305](https://www.pivotaltracker.com/n/projects/2174978/stories/166284305). Please ignore this request.

**Comment by efalayi** [comment]
@brianbirir should this be ignored too? 👇 
https://github.com/AndelaOSP/Andela-Socials/pull/216#issuecomment-499425260

**Comment by brianbirir** [comment]
> @brianbirir should this be ignored too? 👇
> [#216 (comment)](https://github.com/AndelaOSP/Andela-Socials/pull/216#issuecomment-499425260)

No. Work on adding marginal space to improve the look and feel.

**Comment by brianbirir** [comment]
@efalayi This looks great. Thanks.

**Pull request merged**
