### PR TITLE
#161071844 Fix Bug With Calendar Closing Once Clicked

### PR DESCRIPTION
**Pull request by Efosaok**
#### What Does This PR Do?
Fix bug with calendar closing once clicked

#### Description Of Task To Be Completed
Fix bug with calendar closing once clicked

#### Any Background Context You Want To Provide?
N/A

#### How can this be manually tested?
- Log in to the app
- click on the create event floating button
- attempt to select a start date and end date of the event

#### What are the relevant pivotal tracker stories?
[161071844](https://www.pivotaltracker.com/n/projects/2174978)

#### Screenshot(s)
screen shot 2018-10-09 at 7 44 06 am
screen shot 2018-10-09 at 7 44 19 am
screen shot 2018-10-09 at 7 44 38 am

### CODE REVIEW

**Comment by chibujax** [comment]
Tested and it works as expected. Can you squash your commits since its just few lines and one fiile

**Comment by Efosaok** [comment]
@chibujax 
addressed

**Comment by chibujax** [comment]
> @chibujax
> addressed

Thanks, can you fix the merge conflicts?

**Comment by Efosaok** [comment]
fixed as well

**Pull request merged**
