### PR TITLE
#165998501 Event host should be able to add a discussion/group slack channel to an event

### PR DESCRIPTION
**Pull request by samdiano**
#### What Does This PR Do?
This PR adds a slack channel when creating an event 

#### Description Of Task To Be Completed
- add a checkbox to list slack channels to add  when creating an event

#### Any Background Context You Want To Provide?
N/A
#### How can this be manually tested?
- Start the app
- Click on the Button to create an event 
- Click on the `Share to slack` button

#### What are the relevant pivotal tracker stories?
#165998501

#### Screenshot(s)
Screenshot 2019-05-20 at 8 07 36 PM
Screenshot 2019-05-20 at 8 07 08 PM

### CODE REVIEW

**Comment by brianbirir** [comment]
@samdiano thanks for this. However, I'm getting the following error:

```
{
  "data": {
    "createEvent": null
  },
  "errors": [
    {
      "locations": [
        {
          "column": 3,
          "line": 2
        }
      ],
      "message": "Incorrect padding",
      "path": [
        "createEvent"
      ]
    }
  ]
}
```

Have you mapped this field to the GraphQL backend runtime? If I don't select the Slack channel checkbox, I'm able to create an event.

**Comment by samdiano** [comment]
> @samdiano thanks for this. However, I'm getting the following error:
> 
> ```
> {
>   "data": {
>     "createEvent": null
>   },
>   "errors": [
>     {
>       "locations": [
>         {
>           "column": 3,
>           "line": 2
>         }
>       ],
>       "message": "Incorrect padding",
>       "path": [
>         "createEvent"
>       ]
>     }
>   ]
> }
> ```
> 
> Have you mapped this field to the GraphQL backend runtime? If I don't select the Slack channel checkbox, I'm able to create an event.

@brianbirir I have not mapped the field to the backend runtime and it's an optional field, so an event can still be created even without adding a slack channel

**Review by Alameen688 — COMMENTED** [review]
Great work 🎉 @samdiano. Currently, when the user updates the event without selecting a channel, the event is updated with an empty channel id, instead of keeping the previously saved channel id. Kindly help look into that, thank you!

**Comment by samdiano** [comment]
Okay... I will look into it

**Review by Alameen688 — APPROVED** [review]

**Pull request merged**
